# Generated by Django 5.0.1 on 2024-01-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaAlumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaAlumnos.alumno')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaAlumnos.curso')),
            ],
        ),
    ]
